<%@ page language="java" contentType="text/html; charset=UTF-8"
    pageEncoding="UTF-8"%>
var menus = [

	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"轮播图管理",
                        "menuJump":"列表",
                        "tableName":"config"
                    }
                ],
                "menu":"轮播图信息"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"科室管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryKeshi"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"时间段管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryShijianduan"
                    }
                    ,
                    {
                        "buttons":[
                            "新增",
                            "删除",
                            "修改"
                        ],
                        "menu":"职位管理",
                        "menuJump":"列表",
                        "tableName":"dictionaryZhiwei"
                    }
                ],
                "menu":"基础数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"患者管理",
                        "menuJump":"列表",
                        "tableName":"huanzhe"
                    }
                ],
                "menu":"患者管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"单页数据管理",
                        "menuJump":"列表",
                        "tableName":"singleSeach"
                    }
                ],
                "menu":"单页数据管理"
            }
            ,{
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "新增",
                            "修改",
                            "删除"
                        ],
                        "menu":"专家管理",
                        "menuJump":"列表",
                        "tableName":"zhuanjia"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"专家留言管理",
                        "menuJump":"列表",
                        "tableName":"zhuanjiaLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改",
                            "删除"
                        ],
                        "menu":"专家挂号管理",
                        "menuJump":"列表",
                        "tableName":"zhuanjiaOrder"
                    }
                ],
                "menu":"专家管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"管理员",
        "tableName":"users"
    }
	,
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"专家留言管理",
                        "menuJump":"列表",
                        "tableName":"zhuanjiaLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看",
                            "修改"
                        ],
                        "menu":"专家挂号管理",
                        "menuJump":"列表",
                        "tableName":"zhuanjiaOrder"
                    }
                ],
                "menu":"专家管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"专家",
        "tableName":"zhuanjia"
    },
	{
        "backMenu":[
            {
                "child":[
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"专家管理",
                        "menuJump":"列表",
                        "tableName":"zhuanjia"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"专家留言管理",
                        "menuJump":"列表",
                        "tableName":"zhuanjiaLiuyan"
                    }
                    ,
                    {
                        "buttons":[
                            "查看"
                        ],
                        "menu":"专家挂号管理",
                        "menuJump":"列表",
                        "tableName":"zhuanjiaOrder"
                    }
                ],
                "menu":"专家管理"
            }
        ],
        "frontMenu":[

        ],
        "roleName":"患者",
        "tableName":"huanzhe"
    }
];

var hasMessage = '';
